const TAHMIN_SORULAR = [
  // Tarih
  { s: "Türkiye Cumhuriyeti kaç yılında kuruldu?", a: 1923, b: "yılı" },
  { s: "İstanbul'un fethi kaç yılında gerçekleşti?", a: 1453, b: "yılı" },
  { s: "Atatürk kaç yaşında hayatını kaybetti?", a: 57, b: "yaşında" },
  { s: "Türkiye kaç yılında NATO'ya katıldı?", a: 1952, b: "yılında" },
  { s: "Osmanlı İmparatorluğu yaklaşık kaç yıl hüküm sürdü?", a: 624, b: "yıl" },
  { s: "Fransız İhtilali kaç yılında başladı?", a: 1789, b: "yılında" },
  { s: "Birinci Dünya Savaşı kaç yılında sona erdi?", a: 1918, b: "yılında" },
  { s: "Amerika Birleşik Devletleri kaç yılında bağımsızlığını ilan etti?", a: 1776, b: "yılında" },
  { s: "Kurtuluş Savaşı kaç yılında başladı?", a: 1919, b: "yılında" },
  { s: "Lozan Antlaşması kaç yılında imzalandı?", a: 1923, b: "yılında" },
  { s: "İkinci Dünya Savaşı kaç yılında başladı?", a: 1939, b: "yılında" },
  { s: "Berlin Duvarı kaç yılında yıkıldı?", a: 1989, b: "yılında" },
  { s: "Ay'a ilk insanlar kaç yılında ayak bastı?", a: 1969, b: "yılında" },
  { s: "Rönesans yaklaşık kaç yılında başladı?", a: 1300, b: "yılında" },
  { s: "Çanakkale Savaşı kaç yılında yaşandı?", a: 1915, b: "yılında" },

  // Coğrafya & Ölçüler
  { s: "Türkiye'nin yüzölçümü yaklaşık kaç km²'dir?", a: 783562, b: "km²" },
  { s: "Ağrı Dağı kaç metre yüksekliğindedir?", a: 5137, b: "metre" },
  { s: "Boğaziçi Köprüsü kaç metre uzunluğundadır?", a: 1510, b: "metre" },
  { s: "Eyfel Kulesi kaç metre yüksekliğindedir?", a: 330, b: "metre" },
  { s: "Everest Dağı kaç metre yüksekliğindedir?", a: 8849, b: "metre" },
  { s: "Amazon Nehri yaklaşık kaç km uzunluğundadır?", a: 6400, b: "km" },
  { s: "Nil Nehri yaklaşık kaç km uzunluğundadır?", a: 6650, b: "km" },
  { s: "Dünya'nın çapı yaklaşık kaç km'dir?", a: 12742, b: "km" },
  { s: "Türkiye'nin sahil şeridi yaklaşık kaç km'dir?", a: 8333, b: "km" },
  { s: "Büyük Çin Seddi kaç km uzunluğundadır?", a: 21196, b: "km" },
  { s: "Ankara'nın denizden yüksekliği yaklaşık kaç metredir?", a: 938, b: "metre" },
  { s: "Türkiye kaç ilden oluşmaktadır?", a: 81, b: "il" },
  { s: "Karadeniz'in en derin noktası yaklaşık kaç metredir?", a: 2212, b: "metre" },

  // Bilim & Uzay
  { s: "Işık saniyede yaklaşık kaç km yol alır?", a: 300000, b: "km/sn" },
  { s: "Güneş'in Dünya'ya uzaklığı yaklaşık kaç milyon km'dir?", a: 150, b: "milyon km" },
  { s: "Ayın Dünya'ya uzaklığı yaklaşık kaç km'dir?", a: 384400, b: "km" },
  { s: "İnsan vücudunda kaç kemik vardır?", a: 206, b: "kemik" },
  { s: "Dünya'nın yaşı yaklaşık kaç milyar yıldır?", a: 4, b: "milyar yıl" },
  { s: "İnsan vücudunda kaç tür kan grubu (ABO sistemi) vardır?", a: 4, b: "grup" },
  { s: "Bir yılda kaç gün vardır?", a: 365, b: "gün" },
  { s: "Güneş Sistemi'nde kaç gezegen vardır?", a: 8, b: "gezegen" },
  { s: "İnsan beyninin ağırlığı yaklaşık kaç gramdır?", a: 1400, b: "gram" },
  { s: "Su kaç derecede kaynar (deniz seviyesinde)?", a: 100, b: "°C" },
  { s: "Ses saniyede yaklaşık kaç metre yol alır?", a: 343, b: "m/sn" },

  // Nüfus & Demografi
  { s: "Türkiye'nin nüfusu yaklaşık kaç milyondur?", a: 85, b: "milyon" },
  { s: "İstanbul'un nüfusu yaklaşık kaç milyondur?", a: 15, b: "milyon" },
  { s: "Dünya nüfusu yaklaşık kaç milyardır?", a: 8, b: "milyar" },
  { s: "Çin'in nüfusu yaklaşık kaç milyardır?", a: 1, b: "milyar" },
  { s: "Ankara'nın nüfusu yaklaşık kaç milyondur?", a: 5, b: "milyon" },

  // Teknoloji
  { s: "İlk iPhone kaç yılında tanıtıldı?", a: 2007, b: "yılında" },
  { s: "Google kaç yılında kuruldu?", a: 1998, b: "yılında" },
  { s: "Facebook (Meta) kaç yılında kuruldu?", a: 2004, b: "yılında" },
  { s: "Wikipedia kaç yılında kuruldu?", a: 2001, b: "yılında" },
  { s: "İnternet (WWW) kaç yılında kamuya açıldı?", a: 1991, b: "yılında" },
  { s: "İlk bilgisayar oyunu Pong kaç yılında çıktı?", a: 1972, b: "yılında" },

  // Spor
  { s: "FIFA Dünya Kupası ilk kez kaç yılında düzenlendi?", a: 1930, b: "yılında" },
  { s: "Modern Olimpiyatlar kaç yılında başladı?", a: 1896, b: "yılında" },
  { s: "Bir futbol maçı kaç dakika sürer?", a: 90, b: "dakika" },
  { s: "Türkiye 2002 Dünya Kupası'nda kaçıncı oldu?", a: 3, b: "üncü" },
  { s: "100 metre dünya rekoru yaklaşık kaç saniyedir?", a: 9, b: "saniye" },
  { s: "Maraton kaç km'dir?", a: 42, b: "km" },

  // Sanat & Kültür
  { s: "Mona Lisa tablosu yaklaşık kaç cm yüksekliğindedir?", a: 77, b: "cm" },
  { s: "Beethoven kaç yılında doğdu?", a: 1770, b: "yılında" },
  { s: "Shakespeare kaç yılında doğdu?", a: 1564, b: "yılında" },
  { s: "Yunus Emre yaklaşık kaç yılında doğdu?", a: 1238, b: "yılında" },
  { s: "Sistina Şapeli tavanını Michelangelo kaç yılında tamamladı?", a: 1512, b: "yılında" },
  { s: "Mona Lisa tablosu kaç yılında çalındı?", a: 1911, b: "yılında" },
  { s: "Leonardo da Vinci kaç yılında hayatını kaybetti?", a: 1519, b: "yılında" },
  { s: "Selimiye Camii kaç yılında tamamlandı?", a: 1575, b: "yılında" },
  { s: "Harry Potter ve Felsefe Taşı kaç yılında yayımlandı?", a: 1997, b: "yılında" },

  // Tarih (ek)
  { s: "TBMM kaç yılında açıldı?", a: 1920, b: "yılında" },
  { s: "Harf İnkılabı kaç yılında gerçekleşti?", a: 1928, b: "yılında" },
  { s: "Galatasaray Spor Kulübü kaç yılında kuruldu?", a: 1905, b: "yılında" },
  { s: "Titanic kaç yılında battı?", a: 1912, b: "yılında" },

  // Teknoloji (ek)
  { s: "YouTube kaç yılında kuruldu?", a: 2005, b: "yılında" },

  // Coğrafya (ek)
  { s: "K2 Dağı kaç metre yüksekliğindedir?", a: 8611, b: "metre" },
  { s: "Mariana Çukuru'nun derinliği yaklaşık kaç metredir?", a: 10994, b: "metre" },
  { s: "Uluslararası Uzay İstasyonu Dünya'ya yaklaşık kaç km uzaklıktadır?", a: 400, b: "km" },
  { s: "Dünya yüzeyinin yaklaşık yüzde kaçı okyanuslarla kaplıdır?", a: 71, b: "%" },

  // Bilim (ek)
  { s: "Güneş ışığının Dünya'ya ulaşması yaklaşık kaç dakika sürer?", a: 8, b: "dakika" },
  { s: "İnsan vücudunda kaç çift kromozom vardır?", a: 23, b: "çift" },
  { s: "Sağlıklı bir insanın vücut ısısı kaç derecedir?", a: 37, b: "°C" },
  { s: "İnsan vücudunda kaç kaburga kemiği vardır?", a: 24, b: "kemik" },
  { s: "Yetişkin bir insanda kaç diş bulunur?", a: 32, b: "diş" },
  { s: "Bir metreküp kaç litredir?", a: 1000, b: "litre" },
  { s: "Fahrenheit ölçeğinde suyun donma noktası kaç derecedir?", a: 32, b: "°F" },
  { s: "Bir kedide kaç diş bulunur?", a: 30, b: "diş" },

  // Genel Kültür
  { s: "Satranç tahtasında kaç kare vardır?", a: 64, b: "kare" },
  { s: "Bir piyano kaç tuşa sahiptir?", a: 88, b: "tuş" },
  { s: "İngiliz alfabesi kaç harften oluşur?", a: 26, b: "harf" },
  { s: "Bir yılda kaç hafta vardır?", a: 52, b: "hafta" },
  { s: "Bir günde kaç dakika vardır?", a: 1440, b: "dakika" },
  { s: "Bir saatte kaç saniye vardır?", a: 3600, b: "saniye" },
  { s: "Basketbolda hücum süresi kaç saniyedir?", a: 24, b: "saniye" },
  { s: "Standart bir basketbol sahası kaç metre uzunluğundadır?", a: 28, b: "metre" },
  { s: "ABD bayrağında kaç yıldız vardır?", a: 50, b: "yıldız" },
  { s: "Birleşmiş Milletler'e kaç üye devlet vardır?", a: 193, b: "devlet" },

  // Bilim & Uzay (ek)
  { s: "Dünya'nın tek doğal uydusu Ay, Dünya'ya ortalama kaç bin km uzaklıktadır?", a: 384, b: "bin km" },
  { s: "Jüpiter'in çapı, Dünya'nın çapının yaklaşık kaç katıdır?", a: 11, b: "katı" },
  { s: "Suyun fiziksel olarak en yoğun (en ağır) olduğu sıcaklık kaç santigrat derecedir?", a: 4, b: "derece" },
  { s: "Sağlıklı bir yetişkinin kalbi bir günde yaklaşık kaç bin kez atar?", a: 100, b: "bin kez" },
  { s: "DNA'nın çift sarmal yapısı hangi yılda keşfedilmiştir?", a: 1953, b: "yılında" },
  { s: "İnsan vücudundaki en uzun kemik olan uyluk kemiği, boy uzunluğunun yaklaşık yüzde kaçını oluşturur?", a: 25, b: "%" },
  { s: "Dünya'nın Güneş etrafında dönerken sahip olduğu eksen eğikliği yaklaşık kaç derecedir?", a: 23, b: "derece" },
  { s: "Dünya atmosferinin yaklaşık yüzde kaçı oksijenden oluşur?", a: 21, b: "%" },
  { s: "İnsan DNA'sı, şempanze DNA'sı ile yaklaşık yüzde kaç oranında aynıdır?", a: 98, b: "%" },
  { s: "Standart bir insanın kafasında yaklaşık kaç bin adet saç teli bulunur?", a: 100, b: "bin tel" },
  { s: "İnsan gözü akıcı bir video için saniyede en az kaç kareye ihtiyaç duyar?", a: 24, b: "kare/sn" },
  { s: "Bir ışık yılı yaklaşık kaç trilyon kilometredir?", a: 9, b: "trilyon km" },
  { s: "Ay'ın Dünya etrafındaki bir tam turunu tamamlaması yaklaşık kaç gün sürer?", a: 27, b: "gün" },
  { s: "Periyodik Tablo'da kaç adet element bulunmaktadır?", a: 118, b: "element" },
  { s: "Sağlıklı bir yetişkin insanın vücudundaki su oranı ortalama yüzde kaçtır?", a: 60, b: "%" },
  { s: "Yetişkin bir kedinin iskeletinde yaklaşık kaç adet kemik bulunur?", a: 230, b: "kemik" },
  { s: "Dünya'nın merkezindeki çekirdeğin sıcaklığı yaklaşık kaç bin santigrat derecedir?", a: 5, b: "bin derece" },

  // Coğrafya (ek)
  { s: "Türkiye'nin kara sınırı komşusu kaç ülke vardır?", a: 8, b: "ülke" },
  { s: "Geleneksel coğrafi kabule göre Dünya'da kaç kıta bulunmaktadır?", a: 7, b: "kıta" },
  { s: "Ekvator çizgisinin toplam uzunluğu yaklaşık kaç bin kilometredir?", a: 40, b: "bin km" },
  { s: "Türkiye'nin en uzun iç nehri Kızılırmak kaç kilometredir?", a: 1355, b: "km" },
  { s: "Avrupa Birliği'ne üye olan ülke sayısı kaçtır?", a: 27, b: "ülke" },
  { s: "Dünyanın en büyük adası Grönland'ın yüzölçümü yaklaşık kaç milyon km²'dir?", a: 2, b: "milyon km²" },
  { s: "İstanbul Boğazı'nın toplam uzunluğu yaklaşık kaç kilometredir?", a: 30, b: "km" },
  { s: "Ölü Deniz'in yüzeyi deniz seviyesinin yaklaşık kaç metre altındadır?", a: 430, b: "metre" },
  { s: "Afrika kıtasında kaç bağımsız devlet bulunmaktadır?", a: 54, b: "devlet" },
  { s: "Dünyanın en büyük ülkesi Rusya'nın yüzölçümü yaklaşık kaç milyon km²'dir?", a: 17, b: "milyon km²" },
  { s: "Türkiye'nin en büyük gölü Van Gölü'nün yüzölçümü yaklaşık kaç km²'dir?", a: 3713, b: "km²" },
  { s: "İstanbul'un toplam kaç ilçesi vardır?", a: 39, b: "ilçe" },
  { s: "Vatikan'ın yerleşik nüfusu yaklaşık kaçtır?", a: 800, b: "kişi" },
  { s: "Sahra Çölü yaklaşık kaç milyon km²'dir?", a: 9, b: "milyon km²" },
  { s: "New York'taki Özgürlük Heykeli'nin zemin seviyesinden meşale ucuna kadar toplam yüksekliği kaç metredir?", a: 93, b: "metre" },
  { s: "Türkiye ile İran arasındaki kara sınırı yaklaşık kaç kilometredir?", a: 560, b: "km" },
  { s: "Amerika'daki Büyük Kanyon'un (Grand Canyon) uzunluğu yaklaşık kaç kilometredir?", a: 446, b: "km" },

  // Tarih (ek)
  { s: "Hammurabi Kanunları kaç maddeden oluşur?", a: 282, b: "madde" },
  { s: "Gutenberg'in matbaayı icat ettiği yıl yaklaşık kaçtır?", a: 1440, b: "yılında" },
  { s: "Osmanlı'da padişahlık (saltanat) makamı hangi yılda kaldırıldı?", a: 1922, b: "yılında" },
  { s: "Birleşmiş Milletler (BM) hangi yılda kurulmuştur?", a: 1945, b: "yılında" },
  { s: "Berlin Duvarı, yıkılmadan önce kaç yıl boyunca Doğu ve Batı Berlin'i ayırdı?", a: 28, b: "yıl" },
  { s: "Titanic faciasında yaklaşık kaç yüz kişi hayatını kaybetti?", a: 15, b: "yüz kişi" },
  { s: "Magna Carta hangi yılda imzalanmıştır?", a: 1215, b: "yılında" },
  { s: "Topkapı Sarayı'nın inşasına hangi yılda başlandı?", a: 1459, b: "yılında" },
  { s: "Çernobil Nükleer Santrali kazası hangi yılda yaşandı?", a: 1986, b: "yılında" },
  { s: "Romalı diktatör Jül Sezar milattan önce kaç yılında öldürüldü?", a: 44, b: "MÖ" },
  { s: "Süveyş Kanalı hangi yılda trafiğe açıldı?", a: 1869, b: "yılında" },
  { s: "Wright Kardeşler ilk motorlu uçuşu hangi yılda gerçekleştirdi?", a: 1903, b: "yılında" },
  { s: "İkinci Dünya Savaşı (1939-1945) toplam kaç yıl sürmüştür?", a: 6, b: "yıl" },
  { s: "İngiltere'de kadınlara seçme hakkı ilk kez hangi yılda tanındı?", a: 1918, b: "yılında" },
  { s: "Nobel Ödülleri ilk kez hangi yılda verildi?", a: 1901, b: "yılında" },
  { s: "Apollo 11 görevi dünyadan ayrılış ve dönüş dahil toplam kaç gün sürdü?", a: 8, b: "gün" },

  // Spor (ek)
  { s: "Bir basketbol maçında her takımda sahada aynı anda kaç oyuncu bulunur?", a: 5, b: "oyuncu" },
  { s: "Voleybolda bir seti kazanmak için normalde kaç sayıya ulaşmak gerekir?", a: 25, b: "sayı" },
  { s: "Dekatlonda toplam kaç farklı branş vardır?", a: 10, b: "branş" },
  { s: "Wimbledon tenis turnuvası ilk kez hangi yılda oynanmıştır?", a: 1877, b: "yılında" },
  { s: "Standart bir golf sahası tam bir tur için kaç delikten oluşur?", a: 18, b: "delik" },
  { s: "Profesyonel bir boks şampiyonluk maçı en fazla kaç raunt sürer?", a: 12, b: "raunt" },
  { s: "Türkiye Süper Ligi'nde bir takım sezonda toplam kaç maça çıkar?", a: 34, b: "maç" },
  { s: "Michael Phelps Olimpiyat kariyerinde toplam kaç altın madalya kazandı?", a: 23, b: "altın madalya" },
  { s: "Formula 1 araçlarının pistte ulaştığı en yüksek hız rekoru yaklaşık kaç km/s'dir?", a: 372, b: "km/s" },
  { s: "Bowling'de tüm atışlarında strike yapılarak ulaşılabilecek en yüksek puan kaçtır?", a: 300, b: "puan" },
  { s: "Profesyonel buz hokeyi maçının normal süresi (uzatmalar hariç) kaç dakikadır?", a: 60, b: "dakika" },
  { s: "Beysbolda sahada savunma yapan takımın kaç oyuncusu bulunur?", a: 9, b: "oyuncu" },
  { s: "Snooker masasında oyun başlangıcında kaç adet kırmızı top bulunur?", a: 15, b: "kırmızı top" },
  { s: "Masa tenisinde bir set kaç sayıda kazanılır?", a: 11, b: "sayı" },
  { s: "Olimpik triatlon yarışlarında yüzme parkuru kaç metredir?", a: 1500, b: "metre" },
  { s: "Su topunda her takımın sahada (havuzda) kaçar oyuncusu bulunur?", a: 7, b: "oyuncu" },
  { s: "Tour de France genellikle kaç etaptan oluşur?", a: 21, b: "etap" },
  { s: "Badminton'da profesyonel smaçla tüy topun ulaştığı rekor hız yaklaşık kaç km/s'dir?", a: 493, b: "km/s" },

  // Teknoloji & Kültür (ek)
  { s: "Bir satranç oyununa başlarken tahtada toplam kaç taş bulunur?", a: 32, b: "taş" },
  { s: "Standart bir Rubik Küpü'nde toplam kaç adet küçük renkli kare yüzey vardır?", a: 54, b: "kare" },
  { s: "Pi sayısının virgülden sonraki ilk iki basamağı kaçtır?", a: 14, b: "rakamı" },
  { s: "Apple, grafiksel arayüzlü ilk Macintosh bilgisayarını hangi yılda piyasaya sürdü?", a: 1984, b: "yılında" },
  { s: "Instagram hangi yılda kullanıma sunuldu?", a: 2010, b: "yılında" },
  { s: "Twitter'ın (X) başlangıçtaki tweet karakter sınırı kaçtı?", a: 140, b: "karakter" },
  { s: "Dünyada ilk kısa mesaj (SMS) hangi yılda atıldı?", a: 1992, b: "yılında" },
  { s: "DVD teknolojisi ilk kez hangi yılda piyasaya sunuldu?", a: 1995, b: "yılında" },
  { s: "İlk Harry Potter filmi (Felsefe Taşı) hangi yılda vizyona girdi?", a: 2001, b: "yılında" },
  { s: "The Simpsons'ın (Simpsonlar) ilk bölümü hangi yılda yayınlandı?", a: 1989, b: "yılında" },
  { s: "Oscar (Akademi) Ödülleri ilk kez hangi yılda verildi?", a: 1929, b: "yılında" },
  { s: "Standart bir veri CD'sinin depolama kapasitesi yaklaşık kaç megabayttır?", a: 700, b: "MB" },
  { s: "Bir Rubik Küpü'nün yüzeylerinde toplam kaç farklı renk bulunur?", a: 6, b: "renk" },
  { s: "Dünya genelinde bir günde atılan ortalama e-posta sayısı yaklaşık kaç milyardır?", a: 300, b: "milyar" },
  { s: "Titanic filmi kaç dalda Oscar ödülü kazanarak rekor kırdı?", a: 11, b: "ödül" },
  { s: "Star Wars'un ilk filmi (Bölüm 4: Yeni Bir Umut) hangi yılda yayınlandı?", a: 1977, b: "yılında" },
  { s: "Spotify hangi yılda kuruldu?", a: 2006, b: "yılında" },
  { s: "Bluetooth teknolojisi, ismini kaçıncı yüzyılda yaşamış bir Viking kralından almaktadır?", a: 10, b: "yüzyılda" },
  { s: "Standart bir QWERTY masaüstü klavyede kaç adet tuş bulunur?", a: 104, b: "tuş" },
  { s: "Bir web sayfası bulunamadığında karşılaşılan meşhur HTTP hata kodu kaçtır?", a: 404, b: "kodu" },
  { s: "Emojiler ilk kez hangi yılda Japonya'da icat edilmiştir?", a: 1999, b: "yılında" },

  // Bilim & Uzay (ek 2)
  { s: "Bir olimpiyat yüzme havuzunun standart uzunluğu kaç metredir?", a: 50, b: "metre" },
  { s: "İnsan DNA'sında yaklaşık kaç milyar baz çifti bulunur?", a: 3, b: "milyar" },
  { s: "Satürn gezegeninin bilinen kaç adet uydusu vardır?", a: 146, b: "uydu" },
  { s: "Standart bir sinema filmi saniyede kaç kare (fps) gösterilir?", a: 24, b: "kare/sn" },
  { s: "Bir gün tam olarak kaç saniyeden oluşur?", a: 86400, b: "saniye" },
  { s: "Venüs'ün yüzey sıcaklığı ortalama kaç santigrat derecedir?", a: 465, b: "derece" },
  { s: "Ay'ın yerçekimi, Dünya'nın yerçekiminin yaklaşık yüzde kaçıdır?", a: 17, b: "%" },
  { s: "Moğol İmparatorluğu en geniş döneminde yaklaşık kaç milyon km² alanı kaplıyordu?", a: 24, b: "milyon km²" },
  { s: "İnsan vücudundaki kan damarlarının toplam uzunluğu yaklaşık kaç bin kilometredir?", a: 100, b: "bin km" },
  { s: "Hawaii'deki aktif yanardağ Mauna Loa'nın deniz seviyesinden yüksekliği yaklaşık kaç metredir?", a: 4169, b: "metre" },
  { s: "Ganymede (Jüpiter'in uydusu), Merkür gezegeninden yaklaşık yüzde kaç daha büyüktür?", a: 8, b: "%" },
  { s: "Bir su damlasının buluttan yere düşmesi ortalama kaç dakika sürer?", a: 7, b: "dakika" },
  { s: "İnsan iskeletindeki kemiklerin toplam ağırlığı, vücut ağırlığının yaklaşık yüzde kaçıdır?", a: 15, b: "%" },
  { s: "Güneş'in kütlesi, tüm Güneş Sistemi kütlesinin yaklaşık yüzde kaçını oluşturur?", a: 99, b: "%" },
  { s: "Bir insan günde ortalama kaç kez nefes alıp verir?", a: 20000, b: "kez" },
  { s: "İnsan vücudundaki toplam sinir hücresi (nöron) sayısı yaklaşık kaç milyardır?", a: 86, b: "milyar" },
  { s: "İnsan vücudundaki kılcal damarların toplam uzunluğu Dünya'nın çevresini yaklaşık kaç kez dolaşabilir?", a: 2, b: "kez" },
  { s: "İnsan vücudundaki toplam hücre sayısı yaklaşık kaç trilyondur?", a: 37, b: "trilyon" },
  { s: "İnsan vücudundaki en büyük sinir hücresi (nöron) yaklaşık kaç metre uzunluğundadır?", a: 1, b: "metre" },
  { s: "Bir insan ömrü boyunca kalbi ortalama kaç milyar kez atar?", a: 3, b: "milyar" },

  // Biyoloji & Vücut
  { s: "İnsan gözü yaklaşık kaç megapiksel çözünürlüğe eşdeğer bir görüntü algılar?", a: 576, b: "megapiksel" },
  { s: "İnsan vücudundaki en uzun sinir olan siyatik sinir yaklaşık kaç santimetre uzunluğundadır?", a: 90, b: "santimetre" },
  { s: "İnsan vücudundaki en küçük kemik üzengi (stapes) kemiği yaklaşık kaç milimetre uzunluğundadır?", a: 3, b: "milimetre" },
  { s: "İnsan kalbi bir günde yaklaşık kaç litre kan pompalar?", a: 7500, b: "litre" },
  { s: "İnsan tırnakları ayda ortalama kaç milimetre uzar?", a: 3, b: "milimetre" },
  { s: "İnsan vücudundaki toplam kas sayısı kaçtır?", a: 600, b: "kas" },
  { s: "İnsan vücudundaki toplam eklem sayısı kaçtır?", a: 360, b: "eklem" },
  { s: "İnsan vücudundaki toplam ter bezi sayısı yaklaşık kaç milyondur?", a: 3, b: "milyon" },
  { s: "İnsan vücudundaki toplam bakteri sayısı, insan hücrelerinin sayısının yaklaşık kaç katıdır?", a: 10, b: "katı" },
  { s: "Kulaktaki en küçük kas olan stapedius kası yaklaşık kaç milimetre uzunluğundadır?", a: 1, b: "milimetre" },
  { s: "Bir insanın hapşırma hızı saatte yaklaşık kaç kilometreye ulaşabilir?", a: 160, b: "km/s" },
  { s: "Bir insanın ömrü boyunca ürettiği tükürük yaklaşık kaç olimpik havuzu doldurabilir?", a: 2, b: "havuz" },
  { s: "Bir insanın ömrü boyunca ürettiği saçın toplam uzunluğu yaklaşık kaç kilometredir?", a: 950, b: "km" },
  { s: "Bir insan ömrü boyunca ortalama kaç milyon kelime konuşur?", a: 860, b: "milyon" },
  { s: "Bir insan ömrü boyunca ortalama kaç milyon kez göz kırpar?", a: 415, b: "milyon" },
  { s: "Bir insan ömrü boyunca ortalama kaç litre gözyaşı üretir?", a: 62, b: "litre" },
  { s: "Bir insan ömrü boyunca ortalama kaç kez yutkunur?", a: 29200, b: "kez" },
  { s: "Bir insan ömrü boyunca ortalama kaç kez hapşırır?", a: 365, b: "kez" },

  // Hayvanlar & Doğa
  { s: "Bir arı bir kilogram bal üretebilmek için yaklaşık kaç milyon çiçeği ziyaret etmelidir?", a: 4, b: "milyon" },
  { s: "Mavi balinanın kalbi yaklaşık kaç kilogramdır?", a: 180, b: "kilogram" },
  { s: "Bir kar tanesinin kaç köşesi veya kolu vardır?", a: 6, b: "köşe" },
  { s: "Komodo ejderinin maksimum boyu kaç metreye ulaşabilir?", a: 3, b: "metre" },
  { s: "Devekuşunun koşarken ulaştığı maksimum hız saatte kaç kilometredir?", a: 70, b: "km/s" },
  { s: "Rafflesia arnoldii'nin (dünyanın en büyük çiçeği) çapı kaç santimetreye ulaşabilir?", a: 100, b: "santimetre" },
  { s: "Bir insan gözü hayatı boyunca yaklaşık kaç milyon farklı rengi ayırt edebilir?", a: 10, b: "milyon" },
  { s: "Dünyanın en uzun yaşayan ağacı 'Methuselah' adlı çamın yaşı yaklaşık kaçtır?", a: 4853, b: "yıl" },
  { s: "Brezilya gezgin örümceğinin zehri bir insanı yaklaşık kaç dakikada etkisiz bırakabilir?", a: 25, b: "dakika" },
  { s: "Tarihteki en büyük uçak Antonov An-225'in kanat açıklığı kaç metredir?", a: 88, b: "metre" },
  { s: "Titan böceğinin (Titanus giganteus) boyu kaç santimetreye ulaşabilir?", a: 17, b: "santimetre" },
  { s: "Yeşil anakondanın ağırlığı kaç kilograma ulaşabilir?", a: 250, b: "kilogram" },
  { s: "Balina köpekbalığının uzunluğu kaç metreye ulaşabilir?", a: 18, b: "metre" },
  { s: "Mavi balinanın dili tek başına yaklaşık kaç ton ağırlığındadır?", a: 4, b: "ton" },
  { s: "Arjantin karınca kolonisi yaklaşık kaç km² alanı kaplar?", a: 6000, b: "km²" },
  { s: "Çin dev semenderinin ömrü kaç yıla ulaşabilir?", a: 200, b: "yıl" },
  { s: "Japon örümcek yengecinin bacak açıklığı kaç metreye ulaşabilir?", a: 4, b: "metre" },
  { s: "Aslan yelesi medüzasının dokunaçları kaç metreye kadar uzayabilir?", a: 36, b: "metre" },
  { s: "Kapibaranın (dünyanın en büyük kemirgeni) ağırlığı kaç kilograma ulaşabilir?", a: 66, b: "kilogram" },
  { s: "Doğu gorilinin ağırlığı kaç kilograma ulaşabilir?", a: 220, b: "kilogram" },
  { s: "Güney Çin dev semenderinin boyu kaç metreye ulaşabilir?", a: 2, b: "metre" },
  { s: "Bir devekuşu yumurtası yaklaşık kaç adet tavuk yumurtasına eşdeğerdir?", a: 24, b: "yumurta" },
  { s: "Dünyanın en büyük güvesi Atlas güvesinin kanat açıklığı kaç santimetreye ulaşabilir?", a: 30, b: "santimetre" },

  // Tarih (ek 2)
  { s: "Amerikan İç Savaşı hangi yılda sona ermiştir?", a: 1865, b: "yılında" },
  { s: "İlk başarılı sıcak hava balonu uçuşu hangi yılda gerçekleştirildi?", a: 1783, b: "yılında" },
  { s: "Türkiye'nin ilk özel televizyon kanalı Star TV hangi yılda kuruldu?", a: 1989, b: "yılında" },
  { s: "Birinci Dünya Savaşı'nı başlatan Saraybosna Suikastı hangi yılda gerçekleşti?", a: 1914, b: "yılında" },

  // Spor (ek 2)
  { s: "Standart bir bowling oyununda devrilmesi gereken toplam kaç lobut (pin) vardır?", a: 10, b: "lobut" },
  { s: "Bir basketbol potasının çemberinin iç çapı standart olarak kaç santimetredir?", a: 45, b: "santimetre" },
  { s: "Tenis tarihinde kaydedilen en hızlı servis saatte kaç km hıza ulaşmıştır?", a: 263, b: "km/s" },

  // Genel Kültür (ek 2)
  { s: "İstanbul'un Avrupa yakasının telefon alan kodu kaçtır?", a: 212, b: "kod" },
  { s: "Bir tavla oyununda toplam kaç adet pul bulunur?", a: 30, b: "pul" },
  { s: "Atatürk, cumhuriyetin kuruluşundan vefatına kadar kaç yıl cumhurbaşkanlığı yaptı?", a: 15, b: "yıl" },
  { s: "Airbus A380'in maksimum yolcu kapasitesi kaçtır?", a: 853, b: "yolcu" },
  { s: "Tarihteki en kısa savaş Anglo-Zanzibar Savaşı yaklaşık kaç dakika sürdü?", a: 38, b: "dakika" },
  { s: "Bir Formula 1 aracının motoru rölantide dakikada kaç devir yapar?", a: 5000, b: "devir" },
  { s: "Bir golf topunun yüzeyinde ortalama kaç adet küçük çukur (dimple) bulunur?", a: 336, b: "çukur" },
  { s: "İlk ticari cep telefonu Motorola DynaTAC 8000X'in (1983) ağırlığı yaklaşık kaç gramdı?", a: 800, b: "gram" },
  { s: "İnsan midesi boşken yaklaşık kaç mililitre hacme sahiptir?", a: 50, b: "mililitre" },
  { s: "Standart bir iskambil destesinde kaç kart bulunur?", a: 52, b: "kart" },
  { s: "Bir insan ömrü boyunca ortalama kaç yılını uykuda geçirir?", a: 25, b: "yıl" },
  { s: "Bir insan ömrü boyunca ortalama kaç farklı insanla tanışır?", a: 80000, b: "insan" },
  { s: "Bir insan ömrü boyunca ortalama kaç rüya görür?", a: 100000, b: "rüya" },
  { s: "Bir insanın ömrü boyunca yürüdüğü mesafe Dünya'nın etrafını yaklaşık kaç kez döner?", a: 5, b: "kez" },

  // Bilim & Uzay (ek 3)
  { s: "Mars'ın Güneş'e olan ortalama uzaklığı yaklaşık kaç milyon kilometredir?", a: 228, b: "milyon km" },
  { s: "Neptün gezegeni Güneş etrafındaki bir tam turunu yaklaşık kaç Dünya yılında tamamlar?", a: 165, b: "yıl" },
  { s: "Uluslararası Uzay İstasyonu Dünya etrafında bir tam turunu yaklaşık kaç dakikada tamamlar?", a: 90, b: "dakika" },
  { s: "İnsan vücudundaki en uzun kemik olan uyluk kemiği (femur) yetişkin bir erkekte ortalama kaç santimetredir?", a: 48, b: "santimetre" },
  { s: "Sağlıklı bir yetişkin insanın vücudunda yaklaşık kaç litre kan bulunur?", a: 5, b: "litre" },
  { s: "Beyin, vücut ağırlığının sadece yüzde 2'si olmasına rağmen toplam enerjinin yaklaşık yüzde kaçını kullanır?", a: 20, b: "%" },
  { s: "Yetişkin bir insanın derisinin toplam yüzey alanı yaklaşık kaç metrekaredir?", a: 2, b: "metrekare" },
  { s: "Mariana Çukuru'na ilk kez insanlı iniş hangi yılda yapılmıştır?", a: 1960, b: "yılında" },

  // Coğrafya (ek 3)
  { s: "Grönland'ın yüzölçümü Türkiye'nin yüzölçümünün yaklaşık kaç katıdır?", a: 3, b: "katı" },
  { s: "Bir gün tam olarak kaç saatten oluşur?", a: 24, b: "saat" },
  { s: "Nil Nehri'nin geçtiği veya sınır oluşturduğu toplam ülke sayısı kaçtır?", a: 11, b: "ülke" },
  { s: "Dünyadaki tatlı suyun yaklaşık yüzde kaçı Antarktika'daki buzullarda hapsolmuştur?", a: 70, b: "%" },
  { s: "Avrupa kıtasında denize kıyısı olmayan kaç bağımsız ülke vardır?", a: 14, b: "ülke" },
  { s: "Avustralya'nın nüfusu yaklaşık kaç milyondur?", a: 26, b: "milyon" },
  { s: "Ekvator çizgisinin üzerinden geçtiği toplam ülke sayısı kaçtır?", a: 13, b: "ülke" },
  { s: "İzlanda'da aktif veya uykuda olan toplam kaç civarında yanardağ bulunur?", a: 130, b: "yanardağ" },
  { s: "Güney Amerika'daki And Dağları'nın toplam uzunluğu yaklaşık kaç bin kilometredir?", a: 7, b: "bin km" },
  { s: "Türkiye'nin en büyük adası Gökçeada'nın yüzölçümü yaklaşık kaç km²'dir?", a: 280, b: "km²" },
  { s: "Sahra Çölü'nün yüzölçümü, ABD'nin yüzölçümünün yaklaşık yüzde kaçına eşittir?", a: 94, b: "%" },
  { s: "Rusya Federasyonu kaç farklı saat dilimine yayılmıştır?", a: 11, b: "saat dilimi" },
  { s: "Dünyanın en yüksek şelalesi Angel Şelalesi (Venezuela) yaklaşık kaç metre yükseklikten dökülür?", a: 979, b: "metre" },
  { s: "Everest Dağı'nın zirvesindeki oksijen seviyesi deniz seviyesindeki oksijenin yaklaşık yüzde kaçıdır?", a: 33, b: "%" },
  { s: "Dünya üzerindeki tatlı su kaynaklarının yaklaşık yüzde kaçı yeraltı sularından oluşur?", a: 30, b: "%" },
  { s: "Japonya takımadaları toplamda yaklaşık kaç bin adadan oluşur?", a: 14, b: "bin ada" },

  // Tarih (ek 3)
  { s: "Kristof Kolomb'un Amerika'yı keşfettiği ilk yolculuğu kaç gün sürmüştür?", a: 71, b: "gün" },
  { s: "Rusya İmparatorluğu Alaska'yı ABD'ye hangi yılda sattı?", a: 1867, b: "yılında" },
  { s: "Abraham Lincoln hangi yılda suikasta kurban gitmiştir?", a: 1865, b: "yılında" },
  { s: "Karl Marx ve Friedrich Engels'in Komünist Manifesto'su hangi yılda yayımlandı?", a: 1848, b: "yılında" },
  { s: "İngiltere Kraliçesi II. Elizabeth toplam kaç yıl tahtta kalmıştır?", a: 70, b: "yıl" },
  { s: "Osmanlı İmparatorluğu'nda Lale Devri hangi yılda sona erdi?", a: 1730, b: "yılında" },
  { s: "İstanbul'daki Ayasofya (bugünkü yapısı) hangi yılda ibadete açıldı?", a: 537, b: "yılında" },
  { s: "Süveyş Kanalı'nın inşası toplam kaç yıl sürmüştür?", a: 10, b: "yıl" },
  { s: "Çin Seddi'nin yapımı tüm eklemelerle toplamda yaklaşık kaç yüzyıl sürmüştür?", a: 20, b: "yüzyıl" },
  { s: "Boğaziçi Köprüsü (15 Temmuz Şehitler Köprüsü) hangi yılda hizmete açılmıştır?", a: 1973, b: "yılında" },
  { s: "1927'deki ilk cumhuriyet nüfus sayımında Türkiye'nin nüfusu yaklaşık kaç milyondu?", a: 13, b: "milyon" },
  { s: "Galatasaray, UEFA Kupası'nı hangi yılda kazandı?", a: 2000, b: "yılında" },

  // Spor (ek 3)
  { s: "Bir Amerikan futbolu (NFL) sahasının uzunluğu, end zone'lar dahil toplam kaç yardadır?", a: 120, b: "yarda" },
  { s: "Tenis'te Grand Slam unvanı için kazanılması gereken majör turnuva sayısı kaçtır?", a: 4, b: "turnuva" },
  { s: "Olimpiyat altın madalyasının içeriğinde aslında yüzde kaç oranında saf altın bulunur?", a: 1, b: "%" },
  { s: "Muhammed Ali profesyonel boks kariyerinde toplam kaç maç kaybetti?", a: 5, b: "maç" },
  { s: "Macaristan 1954 Dünya Kupası'nda turnuvada toplam kaç gol attı?", a: 27, b: "gol" },
  { s: "Kaydedilmiş en uzun resmi satranç maçı toplam kaç hamle sürdü?", a: 269, b: "hamle" },
  { s: "Standart bir dart tahtasının merkezi (bullseye) yerden tam olarak kaç santimetre yüksekliktedir?", a: 173, b: "santimetre" },
  { s: "NBA'de bir oyuncu tek maçta en fazla kaç faul yapabilir?", a: 6, b: "faul" },

  // Sanat & Kültür (ek 3)
  { s: "Leonardo da Vinci 'Mona Lisa' tablosunu hangi yılda yapmaya başladı?", a: 1503, b: "yılında" },
  { s: "Michael Jackson'ın 'Thriller' albümü hangi yılda çıktı?", a: 1982, b: "yılında" },
  { s: "William Shakespeare'in günümüze ulaşan toplam kaç tiyatro oyunu vardır?", a: 37, b: "oyun" },
  { s: "J.K. Rowling'in Harry Potter serisi toplam kaç kitaptan oluşur?", a: 7, b: "kitap" },
  { s: "'Avatar' filmi hangi yılda vizyona girdi?", a: 2009, b: "yılında" },
  { s: "Sagrada Familia bazilikasının inşasına hangi yılda başlandı?", a: 1882, b: "yılında" },
  { s: "Pablo Picasso 'Guernica' tablosunu hangi yılda yaptı?", a: 1937, b: "yılında" },
  { s: "Leonardo da Vinci 'Son Akşam Yemeği' duvar resmini hangi yılda tamamladı?", a: 1498, b: "yılında" },
  { s: "Beethoven ünlü 9. Senfoni'sini hangi yılda tamamladı?", a: 1824, b: "yılında" },

  // Teknoloji (ek 3)
  { s: "İnternette ilk '.com' alan adı hangi yılda kaydedildi?", a: 1985, b: "yılında" },
  { s: "QWERTY klavye düzeninin patenti hangi yılda alındı?", a: 1878, b: "yılında" },
  { s: "Dünyanın ilk fotoğrafı hangi yılda çekildi?", a: 1826, b: "yılında" },
  { s: "İnsanlık tarihinin ilk yapay uydusu Sputnik 1 kaç kilogram ağırlığındaydı?", a: 83, b: "kilogram" },
  { s: "SMS teknolojisinin karakter sınırı ilk çıktığında kaçtı?", a: 160, b: "karakter" },
  { s: "Google saniyede yaklaşık kaç bin arama isteği işlemektedir?", a: 99, b: "bin" },
  { s: "İlk ticari cep telefonu Motorola DynaTAC 8000X'in şarj süresi yaklaşık kaç saatti?", a: 10, b: "saat" },
  { s: "İlk elektronik genel amaçlı bilgisayar ENIAC'ın ağırlığı yaklaşık kaç tondu?", a: 30, b: "ton" },
  { s: "Dünyanın ilk ticari 3D filmi hangi yılda sinemalarda gösterildi?", a: 1922, b: "yılında" },
  { s: "Rubik Küpü (Zeka Küpü) ilk kez hangi yılda icat edildi?", a: 1974, b: "yılında" },

  // Türkiye
  { s: "Türkiye'nin uluslararası telefon alan kodu (ülke kodu) kaçtır?", a: 90, b: "kodu" },
  { s: "Türkiye Büyük Millet Meclisi toplam kaç milletvekilinden oluşur?", a: 600, b: "milletvekili" },
  { s: "Türkiye'nin yüzölçümü en büyük ili Konya'nın yüzölçümü yaklaşık kaç bin km²'dir?", a: 38, b: "bin km²" },

  // Biyoloji & Doğa (ek 2)
  { s: "Dünyanın en hızlı kuşu gökdoğan dalış sırasında saatte yaklaşık kaç km hıza ulaşır?", a: 389, b: "km/s" },
  { s: "Su aygırları suyun altında ortalama kaç dakika kalabilir?", a: 5, b: "dakika" },
  { s: "Salyangozların ağzında öğütmeye yarayan ortalama kaç adet mikroskobik diş bulunur?", a: 14000, b: "diş" },
  { s: "Ortalama büyüklükte bir kümülüs bulutunun ağırlığı yaklaşık kaç ton olabilir?", a: 500, b: "ton" },
  { s: "Zürafaların boyunlarında kaç adet omur bulunur?", a: 7, b: "omur" },
  { s: "Bir sivrisinek uçarken saniyede ortalama kaç kez kanat çırpar?", a: 500, b: "kez" },
  { s: "Kedilerin her bir kulağında kaç adet kas bulunur?", a: 32, b: "kas" },
  { s: "Dünyada yaşayan karınca nüfusunun insan nüfusuna oranı 1 insana karşılık yaklaşık kaç milyon karıncadır?", a: 2, b: "milyon" },
  { s: "Ölü Deniz'in (Lut Gölü) tuzluluk oranı yaklaşık yüzde kaçtır?", a: 34, b: "%" },
  { s: "İngilizce alfabesinde en çok kullanılan 'E' harfinin kullanım oranı yaklaşık yüzde kaçtır?", a: 11, b: "%" },

  // Genel Kültür (ek 3)
  { s: "Bir yetişkinin ortalama dinlenme kalp atış hızı dakikada yaklaşık kaçtır?", a: 70, b: "atış" },
  { s: "Dünyada her gün yaklaşık kaç milyar fincan kahve tüketilmektedir?", a: 2, b: "milyar" },
  { s: "Her iki elde (parmak ve bilek kemikleri dahil) toplam kaç adet kemik bulunur?", a: 54, b: "kemik" },
  { s: "Bir satranç oyununda her oyuncu kaç piyonla başlar?", a: 8, b: "piyon" },

  // Bilim & Uzay (ek 4)
  { s: "Eyfel Kulesi'nin inşası hangi yılda tamamlandı?", a: 1889, b: "yılında" },
  { s: "Mars'ın Güneş etrafındaki bir tam turu kaç Dünya günü sürer?", a: 687, b: "gün" },
  { s: "Dünyanın en derin gölü olan Baykal Gölü'nün en derin noktası kaç metredir?", a: 1642, b: "metre" },
  { s: "Güneş ışığının Neptün'e ulaşması yaklaşık kaç dakika sürer?", a: 240, b: "dakika" },
  { s: "Samanyolu Galaksisi'nin çapı yaklaşık kaç bin ışık yılıdır?", a: 100, b: "bin ışık yılı" },
  { s: "Jüpiter'in Güneş etrafında bir tam turu yaklaşık kaç Dünya yılı sürer?", a: 12, b: "yıl" },
  { s: "Keops Piramidi inşa edildiğinde orijinal yüksekliği kaç metreydi?", a: 146, b: "metre" },
  { s: "Bir yıldırımın sıcaklığı yaklaşık kaç bin santigrat dereceye ulaşabilir?", a: 30, b: "bin derece" },
  { s: "Dünyanın en yüksek ağacı olan Hyperion Sekoya'sının yüksekliği kaç metredir?", a: 116, b: "metre" },
  { s: "Atmosferdeki gazların yaklaşık yüzde kaçı nitrojendir (azot)?", a: 78, b: "%" },

  // Coğrafya & Yapılar (ek 4)
  { s: "Trans-Sibirya Demiryolu'nun toplam uzunluğu yaklaşık kaç kilometredir?", a: 9289, b: "kilometre" },
  { s: "Süveyş Kanalı'nın uzunluğu yaklaşık kaç kilometredir?", a: 193, b: "kilometre" },
  { s: "Panama Kanalı'nın uzunluğu yaklaşık kaç kilometredir?", a: 82, b: "kilometre" },
  { s: "Pan-Amerikan Karayolu'nun uzunluğu yaklaşık kaç bin kilometredir?", a: 30, b: "bin km" },
  { s: "Death Valley'de (Ölüm Vadisi) ölçülen en yüksek sıcaklık kaç santigrat derecedir?", a: 57, b: "derece" },
  { s: "Antarktika'da kaydedilen en düşük doğal sıcaklık eksi kaç santigrat derecedir?", a: 89, b: "derece" },
  { s: "Grönland'ın yüzde kaçı buzlarla kaplıdır?", a: 80, b: "%" },

  // Tarih (ek 4)
  { s: "İnsanoğlu tekerleği yaklaşık olarak MÖ kaçıncı yılda icat etti?", a: 3500, b: "MÖ yılında" },
  { s: "İlk başarılı kalp nakli ameliyatı hangi yılda gerçekleştirildi?", a: 1967, b: "yılında" },
  { s: "İlk tam metrajlı animasyon filmi Pamuk Prenses ve Yedi Cüceler hangi yılda vizyona girdi?", a: 1937, b: "yılında" },
  { s: "İlk tam sentetik plastik türü olan Bakalit hangi yılda icat edildi?", a: 1907, b: "yılında" },
  { s: "Bilgisayar faresinin (mouse) icat edildiği yıl hangisidir?", a: 1964, b: "yılında" },
  { s: "Sputnik 1 hangi yılda uzaya fırlatıldı?", a: 1957, b: "yılında" },
  { s: "Dünyanın en eski üniversitesi Karaviyyin Üniversitesi hangi yılda kuruldu?", a: 859, b: "yılında" },
  { s: "Viyana Kongresi ile Avrupa haritasının yeniden çizildiği yıl hangisidir?", a: 1815, b: "yılında" },

  // Spor (ek 4)
  { s: "Standart bir dart tahtasında tek bir okla alınabilecek maksimum puan kaçtır?", a: 60, b: "puan" },

  // Hayvanlar & Doğa (ek 2)
  { s: "Köpekbalıkları hayatları boyunca yaklaşık kaç adet diş yenileyebilir?", a: 30000, b: "adet" },
  { s: "Yetişkin bir mavi balinanın sesi su altında yaklaşık kaç kilometre öteden duyulabilir?", a: 800, b: "kilometre" },
  { s: "Yetişkin bir zürafanın boynu ortalama kaç santimetredir?", a: 180, b: "santimetre" },
  { s: "Sinek kuşunun kalbi dakikada en fazla kaç kez atabilir?", a: 1260, b: "atım" },
  { s: "Bir devenin hörgücünde ortalama kaç kilograma kadar yağ depolanabilir?", a: 36, b: "kilogram" },
  { s: "Bir devenin bir oturuşta içebildiği maksimum su miktarı yaklaşık kaç litredir?", a: 113, b: "litre" },
  { s: "Bir çitanın koşarken ulaşabildiği maksimum hız saatte yaklaşık kaç kilometredir?", a: 120, b: "km/s" },
  { s: "Yeryüzüne düşmüş en büyük meteorit olan Hoba meteoritinin ağırlığı yaklaşık kaç tondur?", a: 60, b: "ton" },
  { s: "Dünyadaki konuşulan dillerin sayısı yaklaşık kaç bindir?", a: 7, b: "bin" },
  { s: "Dünya üzerinde bulunan tüm suların yaklaşık yüzde kaçı tatlı sudur?", a: 3, b: "%" },
  { s: "Dünyada üretilen oksijenin yaklaşık yüzde kaçı okyanuslardaki fitoplanktonlar tarafından sağlanır?", a: 70, b: "%" },
  { s: "Bir karpuzun ağırlığının yaklaşık yüzde kaçı sudur?", a: 92, b: "%" },

  // Biyoloji & Vücut (ek 2)
  { s: "Titanic gemisinin toplam uzunluğu kaç metreydi?", a: 269, b: "metre" },
  { s: "Eyfel Kulesi'nin inşasında yaklaşık kaç bin adet perçin kullanıldı?", a: 2500, b: "bin" },
  { s: "İnsan vücudundaki en güçlü kaslardan biri olan çene kası kaç kg kapanma kuvveti üretebilir?", a: 90, b: "kilogram" },
  { s: "Yetişkin bir insanın midesi maksimum gerildiğinde kapasitesi yaklaşık kaç mililitredir?", a: 4000, b: "mililitre" },
  { s: "İnsan vücudundaki en büyük iç organ olan karaciğerin ortalama ağırlığı kaç gramdır?", a: 1500, b: "gram" },
  { s: "Bir kırmızı kan hücresinin insan vücudundaki tam bir turu ortalama kaç saniye sürer?", a: 60, b: "saniye" },
  { s: "Ortalama bir insanın başındaki tüm saç tellerinin günlük uzama toplamı yaklaşık kaç metredir?", a: 35, b: "metre" },
  { s: "Bir insanın hayatı boyunca ürettiği tükürük miktarı ortalama kaç bin litredir?", a: 25, b: "bin litre" },
  { s: "İnsan derisinin bir santimetrekaresinde yaklaşık kaç adet ter bezi bulunur?", a: 100, b: "adet" },
  { s: "Bir insanın bir günde ortalama kaç bin kez göz kırptığı tahmin edilir?", a: 15, b: "bin kez" },

  // Teknoloji & Kültür (ek 4)
  { s: "Apollo 11 Ay'a inerken Dünya'da yaklaşık kaç milyon televizyon izleyicisi vardı?", a: 600, b: "milyon" },
  { s: "Dünyanın en çok satan cep telefonu modeli Nokia 1100 kaç milyon adet satıldı?", a: 250, b: "milyon" },
  { s: "Bir kilo kahve elde etmek için ortalama kaç adet kahve çekirdeği gerekir?", a: 4000, b: "adet" },
  { s: "Uluslararası Uzay İstasyonu (ISS) saatte yaklaşık kaç kilometre hızla Dünya'yı döner?", a: 28000, b: "km/s" },
  { s: "Bir piyanonun tellerindeki toplam gerilim kuvveti yaklaşık kaç tondur?", a: 18, b: "ton" },

  // Bilim & Doğa (ek 5)
  { s: "Bir ahtapotun kaç tane beyni vardır?", a: 9, b: "beyin" },
  { s: "Bir ineğin midesi kaç bölmeden oluşur?", a: 4, b: "bölme" },
  { s: "Güneş sistemindeki en yüksek dağ olan Olympus Mons (Mars) yaklaşık kaç kilometre yüksekliğindedir?", a: 22, b: "kilometre" },
  { s: "Zürafanın dili yaklaşık kaç santimetredir?", a: 45, b: "santimetre" },
  { s: "Bir aslanın kükremesi yaklaşık kaç kilometre uzaktan duyulabilir?", a: 8, b: "kilometre" },
  { s: "Kulağın içinde sesi ileten kaç adet küçük kemikçik bulunur?", a: 3, b: "kemikçik" },
  { s: "Pasifik Okyanusu, yeryüzündeki tüm su kütlesinin yaklaşık yüzde kaçını oluşturur?", a: 46, b: "%" },

  // Tarih (ek 5)
  { s: "Kristof Kolomb Amerika kıtasına hangi yılda ulaştı?", a: 1492, b: "yılında" },
  { s: "Fatih Sultan Mehmet İstanbul'u fethettiğinde kaç yaşındaydı?", a: 21, b: "yaşında" },
  { s: "İkinci Dünya Savaşı hangi yılda sona erdi?", a: 1945, b: "yılında" },
  { s: "J.R.R. Tolkien'in Yüzüklerin Efendisi ilk olarak hangi yılda yayımlandı?", a: 1954, b: "yılında" },
  { s: "Ünlü ressam Van Gogh hayatı boyunca yalnızca kaç tablo satabildi?", a: 1, b: "tablo" },
  { s: "İnternetin başlangıcı sayılan ARPANET hangi yılda kuruldu?", a: 1969, b: "yılında" },

  // Teknoloji (ek 5)
  { s: "Dünyanın ilk bilgisayar programcısı kabul edilen Ada Lovelace kaçıncı yüzyılda yaşadı?", a: 19, b: "yüzyılda" },
  { s: "Bir bayt (byte) kaç bitten (bit) oluşur?", a: 8, b: "bit" },
  { s: "Bitcoin hangi yılda piyasaya sürüldü?", a: 2009, b: "yılında" },

  // Spor (ek 5)
  { s: "Tavla oyununda her oyuncunun taşlarını hareket ettirdiği toplam kaç hane (kapı) vardır?", a: 24, b: "hane" },
  { s: "Modern Olimpiyat Oyunları'nda yaz ve kış oyunları arasındaki yıl farkı kaçtır?", a: 2, b: "yıl" },
  { s: "Bir futbol takımında sahada aynı anda kaç oyuncu bulunur?", a: 11, b: "oyuncu" },
  { s: "NBA'de profesyonel bir basketbol maçı toplam kaç dakika sürer?", a: 48, b: "dakika" },
  { s: "Kış olimpiyatlarında oynanan curling sporunda kullanılan taşın ağırlığı yaklaşık kaç kilogramdır?", a: 20, b: "kilogram" },
  { s: "Bir Amerikan futbolu (NFL) takımının sahada aynı anda kaç oyuncusu bulunur?", a: 11, b: "oyuncu" },

  // Genel Kültür (ek 5)
  { s: "Oscar heykeli yaklaşık kaç kilogram ağırlığındadır?", a: 4, b: "kilogram" },
  { s: "Dünyanın en küçük bağımsız ülkesi Vatikan'ın yüzölçümü yaklaşık kaç hektardır?", a: 44, b: "hektar" },

  // Bilim & Uzay (ek 6)
  { s: "Plüton'un Güneş etrafında bir tam tur atması yaklaşık kaç Dünya yılı sürer?", a: 248, b: "yıl" },
  { s: "Uranüs'ün kaç bilinen uydusu vardır?", a: 27, b: "uydu" },
  { s: "Voyager 1 uzay aracı hangi yılda fırlatıldı?", a: 1977, b: "yılında" },
  { s: "Hubble Uzay Teleskobu hangi yılda uzaya fırlatıldı?", a: 1990, b: "yılında" },
  { s: "Mutlak sıfır kaç eksi derece Celsius'tur?", a: 273, b: "derece (eksi)" },
  { s: "Altının erime noktası kaç derecedir?", a: 1064, b: "°C" },
  { s: "Saf demirin erime noktası yaklaşık kaç derecedir?", a: 1538, b: "°C" },
  { s: "İnsan omurgası kaç omurdan oluşur?", a: 33, b: "omur" },
  { s: "Bir insan elindeki parmak kemiklerinin (falanks) toplam sayısı kaçtır?", a: 14, b: "kemik" },
  { s: "Yetişkin bir köpeğin kaç daimi dişi vardır?", a: 42, b: "diş" },
  { s: "Bir bal arısı saniyede yaklaşık kaç kez kanat çırpar?", a: 200, b: "kez" },
  { s: "Neptün gezegeni hangi yılda keşfedildi?", a: 1846, b: "yılında" },
  { s: "Güneş ışığının Jüpiter'e ulaşması yaklaşık kaç dakika sürer?", a: 43, b: "dakika" },
  { s: "İspanyol gribi salgını hangi yılda başladı?", a: 1918, b: "yılında" },
  { s: "Dünya'nın ortalama albedosu (güneş ışığını yansıtma oranı) yaklaşık yüzde kaçtır?", a: 30, b: "%" },
  { s: "Görünür ışık spektrumunda kırmızı rengin dalga boyu yaklaşık kaç nanometredir?", a: 700, b: "nanometre" },
  { s: "Standart bir konser harpının kaç teli vardır?", a: 47, b: "tel" },
  { s: "Standart bir piyano klavyesinde kaç siyah tuş bulunur?", a: 36, b: "tuş" },

  // Tarih (ek 6)
  { s: "Osmanlı İmparatorluğu'nda ilk matbaa hangi yılda kuruldu?", a: 1727, b: "yılında" },
  { s: "Timur ile Yıldırım Bayezid arasındaki Ankara Savaşı hangi yılda yaşandı?", a: 1402, b: "yılında" },
  { s: "Barbaros Hayreddin Paşa'nın büyük zafer kazandığı Preveze Muharebesi hangi yılda gerçekleşti?", a: 1538, b: "yılında" },
  { s: "Piri Reis ünlü dünya haritasını hangi yılda tamamladı?", a: 1513, b: "yılında" },
  { s: "Kanuni Sultan Süleyman Osmanlı tahtında kaç yıl hüküm sürdü?", a: 46, b: "yıl" },
  { s: "İlk Haçlı Seferi hangi yılda başladı?", a: 1096, b: "yılında" },
  { s: "Kavimler Göçü hangi yılda başladı?", a: 375, b: "yılında" },
  { s: "Endülüs Emevi devletinin son kalesi Gırnata (Granada) hangi yılda düştü?", a: 1492, b: "yılında" },
  { s: "Dünyanın ilk e-postası hangi yılda gönderildi?", a: 1971, b: "yılında" },
  { s: "Dünyanın ilk ticari cep telefonu Motorola DynaTAC hangi yılda piyasaya çıktı?", a: 1983, b: "yılında" },
  { s: "Twitter sosyal medya platformu hangi yılda kuruldu?", a: 2006, b: "yılında" },
  { s: "CD (kompakt disk) hangi yılda ticari olarak piyasaya sürüldü?", a: 1982, b: "yılında" },
  { s: "Formula 1 Dünya Şampiyonası ilk kez hangi yılda düzenlendi?", a: 1950, b: "yılında" },
  { s: "1896 Atina Olimpiyatları'na kaç farklı ülke katıldı?", a: 14, b: "ülke" },
  { s: "Kış Olimpiyat Oyunları ilk kez hangi yılda düzenlendi?", a: 1924, b: "yılında" },
  { s: "Manş Tüneli hangi yılda hizmete açıldı?", a: 1994, b: "yılında" },
  { s: "Everest Dağı'na ilk başarılı tırmanış hangi yılda gerçekleşti?", a: 1953, b: "yılında" },
  { s: "Titanic filmi hangi yılda vizyona girdi?", a: 1997, b: "yılında" },
  { s: "Dünya Sağlık Örgütü (WHO) hangi yılda kuruldu?", a: 1948, b: "yılında" },
  { s: "Düzce'nin il statüsüne kavuştuğu yıl hangisidir?", a: 1999, b: "yılında" },

  // Coğrafya (ek 6)
  { s: "Amerika Birleşik Devletleri kaç eyaletten oluşur?", a: 50, b: "eyalet" },
  { s: "Brezilya kaç farklı ülkeyle kara sınırı paylaşır?", a: 10, b: "ülke" },

  // Sanat & Kültür (ek 6)
  { s: "Ressam Vincent van Gogh kaç yaşında hayatını kaybetti?", a: 37, b: "yaşında" },
  { s: "Pablo Picasso kaç yaşında hayatını kaybetti?", a: 91, b: "yaşında" },
  { s: "Leonardo da Vinci'nin Son Akşam Yemeği tablosunda toplam kaç figür yer alır?", a: 13, b: "figür" },
  { s: "Shakespeare kaç sone (sonnet) yazdı?", a: 154, b: "sone" },
  { s: "Marie Curie hayatı boyunca kaç Nobel Ödülü kazandı?", a: 2, b: "Nobel" },
  { s: "Malala Yousafzai Nobel Barış Ödülü'nü kaç yaşında aldı?", a: 17, b: "yaşında" },
  { s: "Mısır Kraliçesi Kleopatra MÖ kaçıncı yılda hayatını kaybetti?", a: 30, b: "MÖ yılında" },

  // Spor (ek 6)
  { s: "Futbolda sarı ve kırmızı kartlar ilk kez hangi Dünya Kupası'nda kullanıldı?", a: 1970, b: "yılında" },
  { s: "NBA'de bir çeyrek kaç dakika sürer?", a: 12, b: "dakika" },
  { s: "Basketbol potasının yerden yüksekliği kaç santimetredir?", a: 305, b: "santimetre" },
  { s: "Erkekler voleybolunda file yüksekliği kaç santimetredir?", a: 243, b: "santimetre" },
  { s: "Satranç oyununda iki oyuncunun piyon dışı taşlarının toplam sayısı kaçtır?", a: 16, b: "taş" },

  // Genel Kültür (ek 6)
  { s: "1 gigabayt (GB) kaç megabayta (MB) eşittir?", a: 1024, b: "megabayt" },
  { s: "Standart bir zarın karşılıklı iki yüzündeki noktaların toplamı kaçtır?", a: 7, b: "nokta" },
];
