// tarih - kolay
{ q: "Osmanlı'nın kurulduğu Anadolu bölgesi hangisidir?", o: ["Söğüt ve Domaniç (Bitinya)", "Konya ovası", "Ege kıyıları", "Karadeniz kıyısı"], a: 0 },
{ q: "Türkiye Cumhuriyeti'nin ilk başbakanı kimdir?", o: ["İsmet İnönü", "Mustafa Kemal Atatürk", "Rauf Orbay", "Ali Fethi Okyar"], a: 0 },
{ q: "Osmanlı padişahlarından hangisi 'Fatih' unvanını taşır?", o: ["II. Mehmed", "I. Selim", "I. Süleyman", "II. Bayezid"], a: 0 },
{ q: "Birinci Dünya Savaşı'nda Osmanlı'nın savaştığı İngiliz cephelerinden biri neresidir?", o: ["Filistin", "Fransa", "İtalya", "Balkanlar"], a: 0 },
{ q: "Türkiye'de halk eğitimi yaymak amacıyla 1932'de kurulan kurumun adı nedir?", o: ["Halkevleri", "Köy Enstitüleri", "Millet Mektepleri", "İlk Mektepler"], a: 0 },
{ q: "Rusya'nın başkenti Moskova'yı hangi hükümdar 'Üçüncü Roma' olarak ilan etti?", o: ["III. İvan", "Büyük Petro", "Katerina II", "İvan Korkunç"], a: 0 },
{ q: "Atatürk'ün 'Nutuk' adlı büyük söylevini sunduğu şehir neresidir?", o: ["Ankara", "İstanbul", "İzmir", "Samsun"], a: 0 },
{ q: "Osmanlı'nın Avrupa'ya geçişini sağlayan ilk kalıcı üs hangi şehirdir?", o: ["Gelibolu", "Edirne", "Selanik", "Sofya"], a: 0, e: "1354'te deprem sonrası boşalan Gelibolu'yu ele geçiren Osmanlılar Rumeli'ye yerleşmeye başladı." },
{ q: "Türkiye'de ilk demir yolu hattı hangi şehirler arasında döşendi?", o: ["İzmir – Aydın (1866)", "İstanbul – Edirne", "Ankara – Eskişehir", "İzmir – İstanbul"], a: 0 },
{ q: "Orta Çağ'da Avrupa'yı yöneten kilise yapısının başındaki isim unvanı nedir?", o: ["Papa", "Patrik", "Kardinal", "Piskopos"], a: 0 },
{ q: "Osmanlı'da 'Devşirme' sistemiyle yetiştirilen askerlerin oluşturduğu ordu birliğinin adı nedir?", o: ["Yeniçeri Ocağı", "Sipahi Alayı", "Akıncılar", "Kapıkulu Süvarileri"], a: 0 },
{ q: "Hangi antlaşmayla Osmanlı Devleti resmen sona erdi ve Türkiye Cumhuriyeti uluslararası alanda tanındı?", o: ["Lozan Antlaşması (1923)", "Mondros Ateşkesi (1918)", "Sevr Antlaşması (1920)", "Paris Antlaşması (1919)"], a: 0 },
{ q: "Büyük İskender'in öğretmeni kimdir?", o: ["Aristoteles", "Platon", "Sokrates", "Eflatun"], a: 0 },
{ q: "Osmanlı'da ilk matbaayı hangi azınlık topluluklar kurdu?", o: ["Yahudiler (1493)", "Rumlar", "Ermeniler", "Frenk tüccarlar"], a: 0, e: "İspanya'dan sürgün edilen Yahudiler 1493'te İstanbul'da ilk matbaayı kurdu; Müslümanlara matbaa ancak 1727'de açıldı." },
{ q: "Osmanlı'da Fatih Sultan Mehmed'in kurduğu büyük kanunname derlemesine ne ad verilir?", o: ["Kanunname-i Al-i Osman", "Tanzimat Fermanı", "Islahat Fermanı", "Mecelle"], a: 0 },
{ q: "ABD'nin bağımsızlığına ilham veren aydınlanma düşünürü kimdir?", o: ["John Locke", "Jean-Jacques Rousseau", "Voltaire", "Montesquieu"], a: 0 },
{ q: "Osmanlı'nın Balkan topraklarını büyük ölçüde yitirdiği savaş dönemi hangisidir?", o: ["Balkan Savaşları (1912–1913)", "93 Harbi (1877-78)", "Birinci Dünya Savaşı (1914-18)", "Girit Ayaklanmaları (1897)"], a: 0 },
{ q: "Çin'de 1949'da cumhuriyeti kuran komünist lider kimdir?", o: ["Mao Zedong", "Çan Kay-şek", "Deng Şiaoping", "Zhou Enlai"], a: 0 },
{ q: "İkinci Dünya Savaşı sırasında Sovyetler Birliği'nin lideri kimdi?", o: ["Josef Stalin", "Lenin", "Kruşçev", "Brejnev"], a: 0 },
{ q: "Türkiye'de Cumhuriyet'in ilanından önce son olarak toplanan Osmanlı meclisinin adı nedir?", o: ["Meclis-i Mebusan", "Heyet-i Temsiliye", "Divan-ı Hümayun", "Şura-yı Devlet"], a: 0, e: "Son Osmanlı Meclisi 1920'de İstanbul'da toplandı; Misak-ı Millî'yi kabul eden meclis dağıtıldı." },
{ q: "Orta Çağ'da Haçlı Seferlerinin ana hedefi olan kutsal şehir hangisidir?", o: ["Kudüs", "Konstantinopolis", "Mekke", "Roma"], a: 0 },
{ q: "Osmanlı'nın Mısır'ı fetheden padişahı kimdir?", o: ["Yavuz Sultan Selim", "Kanuni Sultan Süleyman", "Fatih Sultan Mehmed", "II. Bayezid"], a: 0 },
{ q: "Fransız İhtilali'nin gerçekleştiği yıl hangisidir?", o: ["1789", "1776", "1799", "1804"], a: 0 },
{ q: "Türkiye'de köy okullarını yaygınlaştırmak amacıyla 1940 yılında kurulan eğitim kurumu nedir?", o: ["Köy Enstitüleri", "Halkevleri", "Darülfünun", "İlk Mektepler"], a: 0, e: "İsmail Hakkı Tonguç önderliğinde açılan bu enstitüler 1954'te kapatılana kadar binlerce köy öğretmeni yetiştirdi." },
{ q: "Osmanlı'da 'Tanzimat' dönemi hangi padişahın saltanatında başladı?", o: ["Abdülmecid I", "Mahmud II", "Abdülaziz", "Abdülhamid II"], a: 0 },
{ q: "Romalıların İtalya yarımadasını tamamlayarak ortak bir egemenlik altına aldıkları dönem kabaca hangi yüzyıla denk gelir?", o: ["MÖ 3. yüzyıl", "MÖ 6. yüzyıl", "MÖ 1. yüzyıl", "MS 1. yüzyıl"], a: 0 },
{ q: "Osmanlı döneminde Türkiye'nin Avrupai anlamda anayasal yönetimi kaç kez ilan edilmiştir?", o: ["2 (1876 ve 1908)", "1 (1876)", "3 (1876, 1908, 1923)", "4 kez"], a: 0, e: "1876 Kanun-u Esasi I. Meşrutiyet, 1908 İkinci Meşrutiyet'i başlattı." },
{ q: "Sanayi Devrimi ile birlikte çalışma koşullarını düzenlemek amacıyla ortaya çıkan ilk işçi örgütlerinin genel adı nedir?", o: ["Sendikalar", "Kooperatifler", "Lonca birlikleri", "Vakıflar"], a: 0 },
{ q: "Amerika kıtasındaki Aztek uygarlığını yıkan İspanyol fatihin adı nedir?", o: ["Hernán Cortés", "Francisco Pizarro", "Diego de Almagro", "Vasco Núñez de Balboa"], a: 0 },
{ q: "İnka uygarlığını çöküşe götüren İspanyol fatihin adı nedir?", o: ["Francisco Pizarro", "Hernán Cortés", "Juan de la Cosa", "Pedro de Valdivia"], a: 0 },
{ q: "Osmanlı'da veziriazamın hükümet binasına verilen genel isim nedir?", o: ["Babıâli", "Topkapı", "Yıldız", "Dolmabahçe"], a: 0 },
{ q: "Birinci Balkan Savaşı'nda Osmanlı'nın yitirdiği topraklar hangi bölgeye aittir?", o: ["Rumeli (Balkanlar)", "Anadolu", "Mısır", "Arabistan"], a: 0 },
{ q: "Türkiye'de 'İstiklal Marşı'nın söz yazarı kimdir?", o: ["Mehmed Akif Ersoy", "Namık Kemal", "Tevfik Fikret", "Yahya Kemal"], a: 0, e: "İstiklal Marşı 12 Mart 1921'de kabul edildi; Mehmed Akif Ersoy ödülü reddetti." },
{ q: "İkinci Dünya Savaşı'nda Almanya'nın Sovyetler Birliği'ni işgal ettiği operasyonun adı nedir?", o: ["Barbarossa Harekâtı", "Overlord Harekâtı", "Blitzkrieg", "Dynamo Harekâtı"], a: 0 },
{ q: "Osmanlı'nın Viyana kapılarına kadar ulaştığı dönem hangi padişah zamanıdır?", o: ["Kanuni Sultan Süleyman (1529) ve IV. Mehmed (1683)", "Yavuz Sultan Selim", "Fatih Sultan Mehmed", "II. Bayezid"], a: 0 },
{ q: "Türkiye'de 1950 seçimlerini kazanarak iktidara gelen parti hangisidir?", o: ["Demokrat Parti", "Cumhuriyet Halk Partisi", "Millet Partisi", "Hürriyet Partisi"], a: 0 },
{ q: "Hangi Osmanlı padişahı Kıbrıs'ı fethetti?", o: ["II. Selim", "Kanuni Sultan Süleyman", "III. Murad", "II. Osman"], a: 0, e: "Kıbrıs 1571'de II. Selim döneminde Osmanlı'ya katıldı; aynı yıl İnebahtı deniz yenilgisi de yaşandı." },
{ q: "Osmanlı İmparatorluğu'nda Türkçe dışındaki resmi yazışma dilleri arasında hangisi vardı?", o: ["Arapça ve Farsça", "Rumca ve Ermenice", "Fransızca ve İtalyanca", "Yunanca ve Latince"], a: 0 },
{ q: "Türkiye'de Milli Mücadele'nin simgesi olan 'Ya istiklal ya ölüm' sloganı hangi belgede yer alır?", o: ["Amasya Genelgesi (1919)", "Erzurum Kongresi bildirgesi", "Nutuk (1927)", "Misak-ı Millî (1920)"], a: 0 },
{ q: "Osmanlı döneminde İstanbul'daki büyük kapalı çarşının adı nedir?", o: ["Kapalıçarşı (Büyük Çarşı)", "Mısır Çarşısı", "Uzunçarşı", "Mahmutpaşa Çarşısı"], a: 0, e: "Fatih Sultan Mehmed tarafından 1461'de inşa ettirilen Kapalıçarşı, dünyanın en büyük ve en eski kapalı çarşılarından biridir." },
{ q: "Kuzey Amerika kıtasında İngiliz sömürgeciliğini başlatan ülke hangisidir?", o: ["İngiltere", "İspanya", "Fransa", "Hollanda"], a: 0 },
{ q: "Türkiye'de Kurtuluş Savaşı sürerken toplanan ve önemli kararlar alan kongre hangisidir?", o: ["Sivas Kongresi (Eylül 1919)", "Erzurum Kongresi (Temmuz 1919)", "Amasya Toplantısı", "Havza Genelgesi"], a: 0, e: "Sivas Kongresi tüm ülkeyi temsil eden ulusal bir kongre özelliği taşıyordu." },
{ q: "Osmanlı Devleti'nin Birinci Dünya Savaşı'na girmesinde belirleyici olan İttihat ve Terakki Cemiyeti'nin üç önemli lideri kimlerdir?", o: ["Enver, Cemal, Talat Paşalar", "Atatürk, İnönü, Karabekir", "Mahmud Şevket, Rauf, Fethi", "Ahmet İzzet, Hüseyin Hüsnü, Tevfik Paşalar"], a: 0 },
{ q: "Osmanlı döneminde 'Tanzimat Fermanı'nı ilan eden sadrazam kimdir?", o: ["Mustafa Reşid Paşa", "Ali Paşa", "Fuat Paşa", "Midhat Paşa"], a: 0, e: "Avrupa'da yetişen ve Batılı ıslahatları savunan Reşid Paşa bu tarihî belgeyi hazırlayıp ilan etti." },
{ q: "Tarihte 'Demir Perde' kavramı neyi ifade eder?", o: ["Soğuk Savaş döneminde Batı ile Doğu Avrupa'yı ayıran siyasi/askerî sınır", "Berlin Duvarı'nın diğer adı", "NATO'nun doğu savunma hattı", "Sovyetler'in nükleer kalkanı"], a: 0 },
{ q: "Osmanlı'nın son döneminde (1908-1918) yönetime hakim olan siyasi hareket hangisidir?", o: ["İttihat ve Terakki Cemiyeti (Jön Türkler)", "Hürriyet ve İtilaf Fırkası", "Osmanlı Ahrar Fırkası", "Fedakaran-ı Millet"], a: 0 },
{ q: "İkinci Dünya Savaşı'nı Avrupa'da başlatan Almanya'nın işgal ettiği ilk ülke hangisidir?", o: ["Polonya (1 Eylül 1939)", "Fransa", "Hollanda", "Belçika"], a: 0 },
{ q: "Osmanlı döneminde Osmanlı'nın Balkan topraklarını kaybetmeye başlamasında belirleyici olan 1877–78 savaşı hangi ülkeyle yapıldı?", o: ["Rusya", "Avusturya-Macaristan", "İngiltere", "Fransa"], a: 0 },
{ q: "Osmanlı Devleti hangi padişah döneminde Selçuklular'ın varisi konumuna geldi?", o: ["Orhan Gazi", "Osman Gazi", "I. Murad", "Yıldırım Bayezid"], a: 0, e: "Orhan Gazi döneminde İznik ve Bursa fethedilerek devlet kurumları sağlamlaştırıldı." },
{ q: "Türkiye'de ilk nüfus sayımı cumhuriyetin kaçıncı yılında yapıldı?", o: ["4. yıl (1927)", "1. yıl (1924)", "10. yıl (1933)", "2. yıl (1925)"], a: 0 },
{ q: "Osmanlı'da 'Anadolu eyaleti' ilk olarak hangi padişah döneminde oluşturuldu?", o: ["I. Murad", "Orhan Gazi", "Yıldırım Bayezid", "I. Mehmed"], a: 0, e: "I. Murad döneminde Osmanlı yönetim yapısı eyalet sistemine geçildi; Anadolu ilk büyük eyaletlerden biri oldu." },
